apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: confident-meninsky-418636641f-scaler
  namespace: apps-release
spec:
  hosts:
    - cc1fbde45ead-in-south-02.mayson.dev
  pathPrefixes:
    - /us-east-2-backstractelb-f2161f-coll-e2b69ba092b24cabb5a42d3cbf073676
  scaleTargetRef:
    name: confident-meninsky-418636641f-depl
    kind: Deployment
    apiVersion: apps/v1
    service: confident-meninsky-418636641f-srv
    port: 80
  replicas:
    min: 0
    max: 10
  scaledownPeriod: 180
  scalingMetric:
    requestRate:
      targetValue: 100
      window: 1m
